name: server-image

description: This is my personal OS image.

base-image: ghcr.io/secureblue/iot-main-hardened
image-version: br-staging-latest-aarch64-42

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    install:
      packages:
        - stunnel
        - unbound
        - podman-compose
        - bind-utils

  - type: script
    scripts:
    - enableservices.sh

  - type: signing

